"""upcoming meetings table

Revision ID: 18a917866dff
Revises: d70af7ff7f5c
Create Date: 2026-07-13 21:45:06.267576

"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


revision = '18a917866dff'
down_revision = 'd70af7ff7f5c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upcoming_meetings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('granicus_event_id', sa.String(), nullable=False),
    sa.Column('granicus_view_id', sa.String(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('starts_at', sa.DateTime(), nullable=True),
    sa.Column('in_progress', sa.Boolean(), nullable=False),
    sa.Column('agenda_url', sa.Text(), nullable=True),
    sa.Column('agenda_text', sa.Text(), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('granicus_event_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('upcoming_meetings')
    # ### end Alembic commands ###
