"""entity geocodes table

Revision ID: 860e70556e11
Revises: b8ff5ff92117
Create Date: 2026-07-14 08:20:11.606624

"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


revision = '860e70556e11'
down_revision = 'b8ff5ff92117'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity_geocodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('lat', sa.Numeric(), nullable=True),
    sa.Column('lng', sa.Numeric(), nullable=True),
    sa.Column('matched_address', sa.Text(), nullable=True),
    sa.Column('geocoded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entity_geocodes')
    # ### end Alembic commands ###
