"""entity_profiles

Revision ID: 8f58bd207876
Revises: fba166193869
Create Date: 2026-07-11 23:17:42.278679

"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


revision = '8f58bd207876'
down_revision = 'fba166193869'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('open_questions', sa.JSON(), nullable=True),
    sa.Column('member_commentary', sa.JSON(), nullable=True),
    sa.Column('through_meeting_id', sa.Integer(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('prompt_version', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['through_meeting_id'], ['meetings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_id')
    )
    op.drop_index(op.f('ix_agenda_items_embedding'), table_name='agenda_items', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_index(op.f('ix_transcript_chunks_embedding'), table_name='transcript_chunks', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_transcript_chunks_embedding'), 'transcript_chunks', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.create_index(op.f('ix_agenda_items_embedding'), 'agenda_items', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_table('entity_profiles')
    # ### end Alembic commands ###
