"""initial schema

Revision ID: abf2688b3a53
Revises: 
Create Date: 2026-07-11 16:47:24.041588

"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


revision = 'abf2688b3a53'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingest_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('phase', sa.String(), nullable=False),
    sa.Column('meetings_processed', sa.Integer(), nullable=True),
    sa.Column('bytes_downloaded', sa.BigInteger(), nullable=True),
    sa.Column('errors', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meetings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('granicus_clip_id', sa.String(), nullable=False),
    sa.Column('granicus_view_id', sa.String(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('meeting_type', sa.String(), nullable=False),
    sa.Column('meeting_date', sa.Date(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('video_url', sa.Text(), nullable=True),
    sa.Column('audio_url', sa.Text(), nullable=True),
    sa.Column('agenda_url', sa.Text(), nullable=True),
    sa.Column('minutes_url', sa.Text(), nullable=True),
    sa.Column('audio_local_path', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('granicus_view_id', 'granicus_clip_id')
    )
    op.create_table('agenda_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_id', 'label')
    )
    op.create_table('entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('canonical_slug', sa.String(), nullable=False),
    sa.Column('first_seen_meeting_id', sa.Integer(), nullable=True),
    sa.Column('current_status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['first_seen_meeting_id'], ['meetings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_slug')
    )
    op.create_table('extractions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('prompt_version', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('raw_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_id', 'prompt_version')
    )
    op.create_table('transcript_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('start_seconds', sa.Numeric(), nullable=True),
    sa.Column('end_seconds', sa.Numeric(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('agenda_item_id', sa.Integer(), nullable=True),
    sa.Column('doc_type', sa.String(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('local_path', sa.Text(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agenda_item_id'], ['agenda_items.id'], ),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_url')
    )
    op.create_table('entity_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias')
    )
    op.create_table('entity_updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('agenda_item_id', sa.Integer(), nullable=True),
    sa.Column('update_text', sa.Text(), nullable=False),
    sa.Column('status_after', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['agenda_item_id'], ['agenda_items.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_id', 'meeting_id')
    )
    op.create_table('votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('agenda_item_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('motion_result', sa.String(), nullable=True),
    sa.Column('vote_breakdown', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['agenda_item_id'], ['agenda_items.id'], ),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_id', 'agenda_item_id', 'description')
    )
    op.create_table('entity_mentions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('agenda_item_id', sa.Integer(), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('transcript_chunk_id', sa.Integer(), nullable=True),
    sa.Column('context_text', sa.Text(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['agenda_item_id'], ['agenda_items.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transcript_chunk_id'], ['transcript_chunks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_id', 'meeting_id', 'document_id', 'transcript_chunk_id', 'role')
    )
    op.create_index('ix_meetings_meeting_date', 'meetings', ['meeting_date'])
    op.create_index('ix_entity_mentions_entity_id', 'entity_mentions', ['entity_id'])
    op.create_index('ix_entity_updates_entity_id', 'entity_updates', ['entity_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entity_mentions')
    op.drop_table('votes')
    op.drop_table('entity_updates')
    op.drop_table('entity_aliases')
    op.drop_table('documents')
    op.drop_table('transcript_chunks')
    op.drop_table('extractions')
    op.drop_table('entities')
    op.drop_table('agenda_items')
    op.drop_table('meetings')
    op.drop_table('ingest_runs')
    # ### end Alembic commands ###
