"""agenda_items.start_seconds (Granicus index points)

Revision ID: d70af7ff7f5c
Revises: 8f58bd207876
Create Date: 2026-07-12 20:32:11.507692

"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


revision = 'd70af7ff7f5c'
down_revision = '8f58bd207876'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agenda_items', sa.Column('start_seconds', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agenda_items', 'start_seconds')
    # ### end Alembic commands ###
