export interface MetricMethod {
  name: string;
  description: string;
  method: string;
  assumptions: string[];
}

export const METRIC_METHODS: MetricMethod[] = [
  {
    name: "New households",
    description: "Estimates how many of the proposed homes are likely to be occupied and contributing to local activity.",
    method: "Proposed housing units adjusted for expected occupancy",
    assumptions: ["Proposed housing units", "Occupancy rate"],
  },
  {
    name: "New residents",
    description: "Translates occupied homes into the number of people expected to live at the development.",
    method: "Occupied households multiplied by persons per multifamily unit (bedroom-mix demographic multipliers)",
    assumptions: ["Occupancy rate", "Multifamily household size"],
  },
  {
    name: "Aggregate household income",
    description: "Approximates the total purchasing power of the development's new households.",
    method: "Households use the mean income of the site's census tract (aggregate income / households), adjusted for new construction",
    assumptions: ["Tract mean household income", "New-construction income premium", "Occupancy rate"],
  },
  {
    name: "New annual spending by category",
    description: "Shows how much new household spending may be available for groceries, dining, retail, services, and entertainment each year.",
    method: "Consumer Expenditure Survey category spending per household, income-scaled with per-category Engel elasticities (necessities grow slower than income)",
    assumptions: ["CES category spending share", "Category income elasticity", "CES scaling factor", "New-construction income premium"],
  },
  {
    name: "Annual capture at a destination",
    description: "Estimates how much of the new spending individual businesses or commercial areas are likely to receive.",
    method: "Huff model over individual retail POIs: joint destination and mode choice with exponential travel-time decay, applied to CES category spending; named clusters are reporting rollups and on-site retail competes as a destination",
    assumptions: ["Destination attractiveness", "Walk impedance decay", "Mode share by spending category", "CES scaling factor"],
  },
  {
    name: "In-city capture share",
    description: "Shows what portion of new spending is expected to remain inside the city instead of flowing elsewhere.",
    method: "Huff model over individual retail POIs: joint destination and mode choice with exponential travel-time decay; share of capture assigned to destinations inside the city boundary",
    assumptions: ["City boundary", "Destination attractiveness", "Walk impedance decay", "Mode share by spending category"],
  },
  {
    name: "On-site jobs removed (existing space)",
    description: "Estimates the jobs associated with existing commercial space that would be displaced by redevelopment.",
    method: "Existing commercial floor area converted to an estimated job count",
    assumptions: ["Existing commercial floor area", "Square feet per office job"],
  },
  {
    name: "On-site retail jobs added",
    description: "Estimates the permanent retail jobs supported by the project's proposed commercial space.",
    method: "Proposed retail floor area converted to an estimated job count",
    assumptions: ["Proposed retail floor area", "Square feet per retail job"],
  },
  {
    name: "Net on-site job change",
    description: "Shows whether the completed project is expected to support more or fewer on-site jobs than the current use.",
    method: "New on-site retail jobs less jobs associated with removed commercial space",
    assumptions: ["Square feet per office job", "Square feet per retail job"],
  },
  {
    name: "New annual spending arriving on foot",
    description: "Estimates the spending that nearby businesses may receive from residents who reach them by walking.",
    method: "Walk-mode share of the joint destination and mode Huff choice, summed across destinations",
    assumptions: ["Mode share by spending category", "CES scaling factor", "Walk impedance decay"],
  },
  {
    name: "Spending arriving on foot at project retail",
    description: "Shows how much resident spending may reach the development's own shops and restaurants on foot.",
    method: "Walk-mode share of the joint Huff choice assigned to the on-site retail destination",
    assumptions: ["On-site retail attractiveness", "Walk impedance decay", "Neighborhood walk share"],
  },
  {
    name: "Implied spending per resident walk trip",
    description: "Provides a reasonableness check by comparing walk-based spending with the total number of expected walking trips.",
    method: "Walk-arriving spending spread across all estimated resident walking trips",
    assumptions: ["Walk trips per resident per day", "Mode share by spending category", "CES scaling factor"],
  },
  {
    name: "New resident walk trips per day",
    description: "Estimates the additional daily foot traffic generated by people living at the development.",
    method: "New residents multiplied by daily walking trips per resident",
    assumptions: ["Walk trips per resident per day", "Multifamily household size", "Occupancy rate"],
  },
  {
    name: "Foot-traffic index change, nearest commercial street segments",
    description: "Highlights the nearby commercial streets most likely to experience a noticeable increase in pedestrian activity.",
    method: "Exact marginal trip flows from the site using POI-weighted destinations and shortest paths, compared with seeded sampled baseline betweenness for the current population",
    assumptions: ["Occupancy rate", "Multifamily household size", "Walk trips per resident per day", "Walk impedance decay"],
  },
  {
    name: "Current real estate tax (site)",
    description: "Establishes the site's existing annual property-tax contribution as the baseline for comparison.",
    method: "Current assessed value multiplied by the real estate tax rate",
    assumptions: ["Current assessed value", "Real estate tax rate"],
  },
  {
    name: "Current value per acre",
    description: "Shows how intensively the site currently contributes taxable value relative to its land area.",
    method: "Current assessed value divided by site area",
    assumptions: ["Current assessed value", "Site area"],
  },
  {
    name: "Projected assessed value",
    description: "Estimates the taxable real estate value of the completed development.",
    method: "Residential value plus the estimated value of proposed commercial floor area",
    assumptions: ["Proposed housing units", "Comparable value per housing unit", "Proposed retail floor area", "Commercial value per square foot"],
  },
  {
    name: "Projected real estate tax",
    description: "Estimates the annual property-tax revenue the completed development could generate.",
    method: "Projected assessed value multiplied by the real estate tax rate",
    assumptions: ["Projected assessed value", "Real estate tax rate"],
  },
  {
    name: "Real estate tax increase",
    description: "Shows the expected gain in annual property-tax revenue compared with the site today.",
    method: "Projected real estate tax less current real estate tax",
    assumptions: ["Projected real estate tax", "Current real estate tax"],
  },
  {
    name: "Projected value per acre",
    description: "Measures how much taxable value the redevelopment could produce from each acre of land.",
    method: "Projected assessed value divided by site area",
    assumptions: ["Projected assessed value", "Site area"],
  },
  {
    name: "Meals tax on captured in-city dining",
    description: "Estimates city meals-tax revenue from new resident spending at restaurants inside the city.",
    method: "Restaurant spending captured inside the city multiplied by the meals tax rate",
    assumptions: ["Restaurant spending", "In-city dining capture share", "Meals tax rate"],
  },
  {
    name: "Local sales tax share on captured in-city retail",
    description: "Estimates the city's share of sales-tax revenue from new retail spending that remains in the city.",
    method: "Retail spending captured inside the city multiplied by the local sales tax share",
    assumptions: ["Retail spending", "In-city retail capture share", "Local sales tax share"],
  },
  {
    name: "Annual service cost - naive per-capita method",
    description: "Provides a conservative upper estimate by assigning each new resident the city's current average service cost.",
    method: "New residents allocated the current general-fund expenditure per resident",
    assumptions: ["New residents", "General-fund expenditure per resident"],
  },
  {
    name: "Annual service cost - marginal framing",
    description: "Estimates the added public-service costs that are more likely to grow because of the development.",
    method: "Per-capita service cost adjusted to include only costs expected to scale with new residents",
    assumptions: ["Naive per-capita service cost", "Marginal cost factor"],
  },
  {
    name: "Net annual fiscal impact - naive per-capita method",
    description: "Tests whether new recurring revenue covers costs under the more conservative per-resident approach.",
    method: "New recurring revenue less the per-capita service-cost estimate",
    assumptions: ["New recurring revenue", "Naive per-capita service cost"],
  },
  {
    name: "Net annual fiscal impact - marginal framing",
    description: "Tests whether new recurring revenue covers the public costs most likely to increase in practice.",
    method: "New recurring revenue less the marginal service-cost estimate",
    assumptions: ["New recurring revenue", "Marginal service cost"],
  },
  {
    name: "Net annual fiscal impact range",
    description: "Presents a practical range of possible yearly gains or losses rather than relying on one cost estimate.",
    method: "Range bounded by the naive per-capita and marginal service-cost estimates",
    assumptions: ["New recurring revenue", "Naive per-capita service cost", "Marginal service cost"],
  },
];
